import { Book } from "../component/books/BookCard";

export const books:Book[] = [
    {
        id: 1,
        title: "Twilight",
        author: "Stephenie Meyer",
        pageNum: 464,
        Publisher: "Little, Brown Book Group",
        description: "When 17 year old Isabella Swan moves to Forks, Washington to live with her father she expects that her new life will be as dull as the town. But in spite of her awkward manner and low expectations, she finds that her new classmates are drawn to this pale, dark-haired new girl in town. But not, it seems, the Cullen family. These five adopted brothers and sisters obviously prefer their own company and will make no exception for Bella. Bella is convinced that Edward Cullen in particular hates her, but she feels a strange attraction to him, although his hostility makes her feel almost physically ill. He seems determined to push her away - until, that is, he saves her life from an out of control car.Bella will soon discover that there is a very good reason for Edward's coldness. He, and his family, are vampires - and he knows how dangerous it is for others to get too close.",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1700522826i/41865.jpg",
        revue: [],
        likes: 3,
    },
    {
        id: 2,
        title: "Midnight Sun",
        author: "Stephenie Meyer",
        pageNum: 662,
        Publisher: "Little, Brown Book Group",
        description: "Bestselling author Stephenie Meyer makes a triumphant return to the world of Twilight with this highly anticipated companion: the iconic love story of Bella and Edward told from the vampire's point of view. When Edward Cullen and Bella Swan met in Twilight, an iconic love story was born. But until now, fans have heard only Bella's side of the story. At last, readers can experience Edward's version in the long-awaited companion novel, Midnight Sun. This unforgettable tale as told through Edward's eyes takes on a new and decidedly dark twist. Meeting Bella is both the most unnerving and intriguing event he has experienced in all his years as a vampire. As we learn more fascinating details about Edward's past and the complexity of his inner thoughts, we understand why this i...",
        image: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/713zye8OZFL._AC_UF1000,1000_QL80_.jpg",
        revue: [],
        likes: 8,
    },
    {
        id: 3,
        title: "New Moon",
        author: "Stephenie Meyer",
        pageNum: 563,
        Publisher: "Little, Brown Book Group",
        description: "In New Moon, Stephenie Meyer delivers another irresistible combination of romance and suspense with a supernatural twist. The 'star-crossed' lovers theme continues as Bella and Edward find themselves facing new obstacles, including a devastating separation, the mysterious appearance of dangerous wolves roaming the forest in Forks, a terrifying threat of revenge from a female vampire and a deliciously sinister encounter with Italy's reigning royal family of vampires, the Volturi. Passionate, riveting, and full of surprising twists and turns, this vampire love saga captures the struggle between defying our instincts and satisfying our desires. This is a love story with bite.",
        image: "https://static-01.daraz.com.bd/p/1dd6f709a42694c4ef54275aea4cae15.jpg",
        revue: [],
        likes: 5,
    },
    {
        id: 4,
        title: "Eclipse",
        author: "Stephenie Meyer",
        pageNum: 688,
        Publisher: "Gramedia Pustaka Utama",
        description: "Bella yakin ia hanya mencintai Edward. Tapi benarkah begitu? Sebab sekali ini Jacob takkan tinggal diam; ia akan membuktikan kepada Bella, bahwa gadis itu juga mencintainya. Ada sesuatu yang Edward ingin tak kuketahui. Sesuatu yang takkan pernah dirahasiakan Jacob dariku. Sesuatu yang membuat keluarga Cullen dan kawanan werewolf rela melakukan gencatan senjata dan bekerja sama bahu-membahu... Sesuatu yang kunanti-nantikan. Sesuatu yang meskipun tak pernah kuharapkan bakal terjadi, toh terjadi juga. Di Seattle terjadi serangkaian pembunuhan misterius, sementara Victoria, vampir yang menyimpan kebencian terhadap Bella, terus melanjutkan aksi balas dendamnya. Sekali lagi Bella menemukan dirinya terperangkap dalam bahaya. Di tengah-tengah semua itu, ia juga dipaksa untuk memilih antara cint...",
        image: "https://www.mayobooks.ie/image/cache/catalog/Eclipse-1000x1000.jpg",
        revue: [],
        likes: 9,
    },
    {
        id: 5,
        title: "Breaking Dawn",
        author: "Stephenie Meyer",
        pageNum: 864,
        Publisher: "Gramedia Pustaka Utama",
        description: "Bila kau mencintai orang yang akan membunuhmu, kau tak punya pilihan. Bila nyawamu satu-satunya yang harus kauberikan untuk orang yang kaucintai, bagaimana mungkin kau tidak memberikannya? Bagi Bella Swan, mencintai dan dicintai vampir bernama Edward adalah bagaikan khayalan dan mimpi buruk yang dirajut jadi satu ke dalam kenyataan. Bukan itu saja, hubungannya yang sangat istimewa dengan Jacob Black sang werewolf, ternyata menyeret Bella ke pilihan-pilihan pelik yang membuat hati keduanya tercabik-cabik. Tapi konon cinta harus memilih, dan karenanya Bella harus memutuskan. Dan sebagai orang yang sangat mengenal Bella, Jacob tahu persis apa keputusan gadis itu. Lalu sanggupkah Jacob meninggalkan Bella selamanya untuk menyembuhkan lukaluka hatinya sendiri? Dan ketika Bella membutuhkannya, sanggupkah Jacob mengatakan tidak?",
        image: "https://img1.od-cdn.com/ImageType-400/1191-1/C91/930/8E/%7BC919308E-2BB5-4F24-80E8-BB7907A69DE2%7DImg400.jpg",
        revue: [],
        likes: 9,
    },
]